backend:
  name: github
  repo: GeorgiaStateDefenseForce/gastateguard.com
  branch: main # Branch to update (optional; defaults to master)
  publish_mode: editorial_workflow
media_folder: 'images'
collections:
  - name: 'blog'
    label: 'Frontline News'
    folder: '_posts/'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: 'pages'
    label: 'Pages'
    folder: 'pages/'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown" }